#!/usr/bin/env python3
"""embed.py — bake fonts (and later icons) into C arrays for the editor.

Usage:
    python3 tools/embed.py build/fonts_embedded.h \
        font_ui=assets/fonts/InterVariable.ttf \
        font_mono=assets/fonts/JetBrainsMono-Regular.ttf

Generates a header with one `static const unsigned char <name>[] = {…};`
plus a length macro per file. The editor builds its imgui font atlas from
these arrays — no runtime files to ship.
"""
import os
import sys


def emit(out, name, path):
    data = open(path, "rb").read()
    out.write(f"static const unsigned char {name}[] = {{\n")
    for i in range(0, len(data), 16):
        chunk = data[i : i + 16]
        out.write("  " + ",".join(str(b) for b in chunk) + ",\n")
    out.write("};\n")
    out.write(f"static const int {name}_len = {len(data)};\n\n")
    print(f"  embedded {path} -> {name} ({len(data)} bytes)")


def main():
    header, *kv = sys.argv[1:]
    if not header or len(kv) < 1:
        print(__doc__)
        sys.exit(1)
    os.makedirs(os.path.dirname(header) or ".", exist_ok=True)
    with open(header, "w") as out:
        out.write("// auto-generated by tools/embed.py — do not edit\n")
        out.write("#pragma once\n\n")
        for item in kv:
            name, path = item.split("=", 1)
            emit(out, name, path)


if __name__ == "__main__":
    main()
